### ISSUE TITLE
Migrate To RoboSail Organization

### ISSUE THREAD

**Issue by srlm-io** [RoboSail/RoboSail#2]
@soltaniehha: What do you think about migrating this repository to a RoboSail organization? I think it would be good so that @dianerobosail can keep everything under the organization name.

I've set the organization up here: https://github.com/RoboSail. You should have received an invite to become a member. I don't know what level it defaults you to when you accept, so if it's not admin then I can change that then. From there, it's just following the transfer steps:

https://help.github.com/articles/transferring-a-repository/#transferring-from-a-user-to-an-organization

What do you think?

**Comment by srlm-io** [comment]
@soltaniehha Thanks!

**Comment by soltaniehha** [comment]
Not a problem!
